---
image: "ghcr.io/mullholland/docker-molecule-shell:latest"

services:
  - docker:dind

stages:
  - linting
  - "default-previous"
  - "default-current"

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

linting:
  stage: linting
  variables:
    COMMAND: "lint"
  script:
    - "command=${COMMAND} /opt/molecule.sh"


"default-previous":
  needs:
    - "linting"
  stage: "default-previous"
  variables:
    SCENARIO: "default"
    ANSIBLE: "previous"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"default-current":
  needs:
    - "linting"
  stage: "default-current"
  variables:
    SCENARIO: "default"
    ANSIBLE: "current"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"
