---
# Ansible managed

name: "Ansible Molecule"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    types: [assigned]
  schedule:
    - cron: '31 16 16 * *'

jobs:
  linting:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/mullholland/docker-molecule-shell:latest
      env:
        command: "lint"
        scenario: "default"
        ansible: "current"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: molecule lint
        run: scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} command=${command} /opt/molecule.sh

  "default_previous":
    runs-on: ubuntu-20.04
    needs:
      - linting
    container:
      image: ghcr.io/mullholland/docker-molecule-shell:latest
    strategy:
      fail-fast: false
      matrix:
        platform: [debian10, debian11]  # yamllint disable-line rule:line-length
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: molecule test
        run: scenario=default ansible=previous platform=${{ matrix.platform }} command=test /opt/molecule.sh

  "default_current":
    runs-on: ubuntu-20.04
    needs:
      - linting
    container:
      image: ghcr.io/mullholland/docker-molecule-shell:latest
    strategy:
      fail-fast: false
      matrix:
        platform: [debian10, debian11]  # yamllint disable-line rule:line-length
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: molecule test
        run: scenario=default ansible=current platform=${{ matrix.platform }} command=test /opt/molecule.sh
